name = "uffo-studio"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "out"

[vars]
# Variables públicas aquí

# Para la API key, usar variables de entorno secretas en producción